-- 1. 非構造データの取り込み(ステージング)
CREATE OR REPLACE STAGE BRONZE.SNOWVILL.DEMO_STG
  encryption = (type = 'snowflake_sse') 
  DIRECTORY = (ENABLE = TRUE);

-- 2. ステージのバージョン管理
CREATE OR REPLACE STREAM BRONZE.SNOWVILL.DEMO_ST 
ON DIRECTORY(@BRONZE.SNOWVILL.DEMO_STG);


